CREATE DATABASE test2;

use test2;
CREATE TABLE users(
id INT(11) UNSIGNED AUTO_INCREMENT PRIMARY KEY,
firstname VARCHAR(30) NOT NULL,
lastname VARCHAR(30) NOT NULL,
userid VARCHAR(50) NOT NULL,
house VARCHAR(50) NOT NULL,
location VARCHAR(30) NOT NULL,
date TIMESTAMP 
); 